// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__aside': string;
  'root__btn-backward': string;
  'root__content': string;
}
export const cssExports: CssExports;
export default cssExports;
