// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__label': string;
  'root__start-switcher': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
