export enum Actions {
  // core
  'CORE_SET_API_KEY',
  // gallery
  'GALLERY_SET_FLAG',
  'GALLERY_SET_DATA',
  'GALLERY_SET_QUERY',
  'GALLERY_SET_PAGINATION',
  'GALLERY_SET_CONTENT_SCROLL_TOP',
  // detailsPage
  'DETAILS_PAGE_FETCH_BY_ID',
  'DETAILS_PAGE_SET_DATA',
  'DETAILS_PAGE_SET_FLAG',
  'DETAILS_PAGE_RESET',
}
