// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__input': string;
  'root__magnifying-glass': string;
}
export const cssExports: CssExports;
export default cssExports;
