// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__parameter': string;
  'root__parameters-box': string;
  'root__search-bar': string;
}
export const cssExports: CssExports;
export default cssExports;
