// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__btn': string;
  'root__btn-layer': string;
  'root__collapsable': string;
  'root__input': string;
}
export const cssExports: CssExports;
export default cssExports;
