// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root_active': string;
  'root_input': string;
  'root_not-active': string;
}
export const cssExports: CssExports;
export default cssExports;
