// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content-item': string;
  'content-item__Image': string;
  'content-item__skeleton': string;
  'content-item__text': string;
  'fade-in': string;
  'root': string;
  'root__cards': string;
  'root__spinner-box': string;
}
export const cssExports: CssExports;
export default cssExports;
